# Generated by Django 5.2.10 on 2026-01-25 17:59

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(
                storage=core.storage.OverwriteStorage(),
                upload_to=core.models.folder_path_handler,
            ),
        ),
    ]
